language: go

go:
  - 1.5.1

addons:
  apt:
    packages:
    - cpio
    - debhelper
    - dpkg-dev
    - make
    - perl
    - rpm
    - fakeroot
    
before_script:
  - wget http://archive.ubuntu.com/ubuntu/pool/main/a/alien/alien_8.86_all.deb
  - dpkg -X alien_8.86_all.deb alien
  - rm -fr alien_8.86_all.deb
  - export PATH=$PATH:$PWD/alien/usr/bin
  - export PERL5LIB=$PERL5LIB:$PWD/alien/usr/share/perl5
  
script: 
  - make build-all rpm-all deb-all deploy-prep

notifications:
  - slack: emccode:uuShEq2FwEReY2r5jDLve8uD
  
before_deploy: 
  - ./.bintray-decapitate.sh
  
deploy:
  - provider: bintray
    file: .bintray-stupid-filtered.json
    user: akutz
    key: 60b9a06880345572303b65d079dd9f82d16fb8b6
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true) && ($TRAVIS_BRANCH = master || $IGNORE_BRANCH_CONDITION = true)
      
  - provider: bintray
    file: .bintray-staged-filtered.json
    user: akutz
    key: 60b9a06880345572303b65d079dd9f82d16fb8b6
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ -rc[[:digit:]]+$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)
  
  - provider: bintray
    file: .bintray-stable-filtered.json
    user: akutz
    key: 60b9a06880345572303b65d079dd9f82d16fb8b6
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)
