language: go
go:
  - 1.6
go_import_path: github.com/emccode/libstorage
before_install:
  - git config --global 'url.https://github.com/.insteadof' 'git://github.com/'
  - git config --global 'url.https://github.com/.insteadof' 'git@github.com:'
install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover
script:
  - make -j codecov
