site_name: REX-Ray
site_url: https://github.com/emccode/rexray
repo_url: https://github.com/emccode/rexray.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs/.themes/yeti

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
    - Release Notes: about/release-notes.md
