site_name: REX-Ray
site_url: https://github.com/codedellemc/rexray
repo_url: https://github.com/codedellemc/rexray.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs-themes/yeti
site_favicon: favicon.png
extra_css:
    - css/codedellemc.css
    - css/codedellemc-font.css
    - css/hX.css
markdown_extensions:
    - admonition
    - toc:
        permalink: true
pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/config.md
    - Storage Providers: user-guide/storage-providers.md
    - CSI: user-guide/csi.md
    - libStorage: user-guide/libstorage.md
    - Schedulers: user-guide/schedulers.md
    - Docker Plug-ins: user-guide/docker-plugins.md
    - Applications: user-guide/applications.md
    - Demo: user-guide/demo.md
    - Troubleshooting: user-guide/troubleshooting.md
    - Usage: user-guide/usage.md
- Developers Guide:
    - Project Guidelines: dev-guide/project-guidelines.md
    - Build Reference: dev-guide/build-reference.md
    - Release Process: dev-guide/release-process.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
    - Release Notes: about/release-notes.md
